# -*- coding: utf-8 -*-
"""OptionPricingModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NyJxEIUNKspYs7Qcy7jOwBVtcRhZAZ-c
"""

import math
from scipy.stats import norm

"""# Definitions"""

## Definitions
UP =  231.10 # Underlying Price
SP = 245 # Strike Price
TE = 0.1 # Time to Expiration
RFR = 0.0422 # Risk Free Rate
V = 0.333 # Volatility

"""# Black-Scholes Merton Model

d1 = ((Underlying Price / Strike Price) + (Risk Free Rate + (0.5)Volatility ^ 2) Time to Expiration) / (Volatility x square root(Time to Expiration)
"""

d1 = (math.log(UP/SP) + (V + 0.5 * V **2 ) * TE ) / (V * math.sqrt(TE))

"""d2 = d1 - Volatility x square root (Time to Expiration)"""

d2 = d1 - (V * math.sqrt(TE))

"""Calculate the call option price"""

C = UP * norm.cdf(d1) - SP * math.exp(-RFR * TE) * norm.cdf(d2)

"""Calculate the put option price"""

P = UP * math.exp(-RFR * TE) * norm.cdf(-d2) - SP * norm.cdf(-d1)

"""Print Result"""

print( 'The value of d1 is: ', round(d1, 4))
print( 'The value of d2 is: ', round(d2, 4))
print('The price of the call option is: $', round(C, 2))
print( 'The price of the put option is: $', round(P, 2))